server:
  port: 8080

spring:
  application:
    name: USER-SERVICE

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/ExamServer
    username: postgres
    password: pgAdmin
    driverClassName: org.postgresql.Driver  